### ISSUE TITLE
Plans on enabling multi-GPU training for OpenOrca finetuning?

### ISSUE THREAD

**Issue by matthiasgeihs** [daniel-furman/sft-demos#1]
Hey, found this repository via your hugging face model `dfurman/mpt-7b-instruct-openorca`. This looks very useful!

I am currently mostly working with 2xA100 40GB.
Are there any plans to enhance the scripts to make finetuning work on multiple GPUs?

**Comment by daniel-furman** [comment]
Yes - thanks for the question! I am planning on adapting the multi-GPU tutorial from Hugging Face that uses the FDSP method for multi-GPU training. Planning on doing sft with mpt-30b and perhaps falcon-40b with this multi-gpu tutorial. Don't have a timeline on when this will be ready though, could be a week or a month depending on my free time. 

https://github.com/daniel-furman/sft-demos/blob/main/sft/multi_gpus/fsdp/hf_tutorials/fsdp_with_peak_mem_tracking.py

^ you could try to edit the above yourself - if you do, lmk!

**Comment by matthiasgeihs** [comment]
Thx for the response. I'll let you know if I try and how things are going.
