### ISSUE TITLE
Roadmap to include SFT + Alignment

### ISSUE THREAD

**Issue by vikram71198** [daniel-furman/sft-demos#2]
Hi @daniel-furman , I want to start off by saying this is a really cool repo! These scripts are extremely useful to a novice starting off with these libraries.

I mostly just see SFT notebooks. Do you have any plans to add in alignment as well (RLHF, RLAIF, PPO, DPO) after SFT-ing your models? Something along the lines of what HuggingFace has [here](https://github.com/huggingface/alignment-handbook).

If you're open to contributors, I'd love to join too if you have any other ideas. 

Cheers!

**Comment by daniel-furman** [comment]
I am planning on adding alignment (DPO is next) - yet, not open to contributors at this time. Thanks for your nice comments and interest!
